version: '3.9'
services:
  hlds:
    build: .
    ports:
      - "27015:27015/udp"
    environment:
      - SERVER_NAME=CSDS
      - DEFAULT_MAP=de_dust2
      - SV_LAN=0
      - MAX_PLAYERS=16
      - GAMEMODE=classic
      - SV_AIM=0
      - PAUSABLE=0
      - SV_MAXSPEED=320
      - MP_TIMELIMIT=20
      - SV_CHEATS=0
